# import = ["~/.config/alacritty/rose-pine.toml"]
import = ["~/.cache/wal/alacritty-colors.toml"]

[shell]
	program = "/bin/zsh"
	args = ["-l"]

[window]
	padding = { x = 2, y = 0 }
	dynamic_padding = true
