exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=waybar -c ~/.config/waybar/config.jsonc
exec-once=solaar -w hide
exec-once=swww init
exec-once=udiskie
exec-once=/home/prin/.config/hypr/script.sh
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=wal -R 

# startup apps
exec-once=[workspace 8  silent] flatpak run com.todoist.Todoist
exec-once=[workspace 9  silent] spotify
